[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@eth-optimism/=node_modules/@eth-optimism/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'openzeppelin-solidity-2.3.0/=node_modules/openzeppelin-solidity-2.3.0/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]
# libraries = [
#     "contracts/libraries/MerkleTree.sol:MerkleTree:0x806ec726fc022525a478608e162f528b5deee788",
#     "contracts/libraries/AelinAllowList.sol:AelinAllowList:0x3c312abcef37e63e8ca3ac0c370fb1f8e74c0cec",
#     "contracts/libraries/AelinNftGating.sol:AelinNftGating:0xfa0de0e65292c12ed22c80da331ca2806a84215d",
#     "contracts/libraries/NftCheck.sol:NftCheck:0xa7a86ec3c266435c580354d8c9a33b1bc91697a7"
# ]
fuzz_max_global_rejects = 50000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config