[default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@eth-optimism/=node_modules/@eth-optimism/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'openzeppelin-solidity-2.3.0/=node_modules/openzeppelin-solidity-2.3.0/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]
# libraries = ["contracts/libraries/AelinAllowList.sol:AelinAllowList:0xd1eC5c6B49EB207f4eD6Bcf1C6eb1b23E02854a7", "contracts/libraries/AelinNftGating.sol:AelinNftGating:0xc589A2b87D7fd18D262BE9FCcd47Dc6615284005"]
fuzz_max_global_rejects = 50000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config