
[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@eth-optimism/=node_modules/@eth-optimism/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'openzeppelin-solidity-2.3.0/=node_modules/openzeppelin-solidity-2.3.0/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]

fuzz_max_global_rejects = 50000000
 
#libraries = [
#    "contracts/libraries/AelinAllowList.sol:AelinAllowList:0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
#    "contracts/libraries/MerkleTree.sol:MerkleTree:0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
#    "contracts/libraries/AelinNftGating.sol:AelinNftGating:0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
#]
